/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppPaymentForm {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppPaymentFormElement extends Components.AppPaymentForm, HTMLStencilElement {
    }
    var HTMLAppPaymentFormElement: {
        prototype: HTMLAppPaymentFormElement;
        new (): HTMLAppPaymentFormElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-payment-form": HTMLAppPaymentFormElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppPaymentForm {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-payment-form": AppPaymentForm;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-payment-form": LocalJSX.AppPaymentForm & JSXBase.HTMLAttributes<HTMLAppPaymentFormElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
